# Generated by Django 4.2.21 on 2025-01-30 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_get', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('employee_first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('employee_last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('employee_profile', models.ImageField(blank=True, null=True, upload_to='employee/profile')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10, null=True)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='single', max_length=50, null=True)),
                ('children', models.IntegerField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('is_from_onboarding', models.BooleanField(blank=True, default=False, editable=False, null=True)),
                ('is_directly_converted', models.BooleanField(blank=True, default=False, editable=False, null=True)),
                ('biometric_employee_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Biometric Employee ID')),
                ('biometric_employee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Biometric Employee Name')),
            ],
            options={
                'ordering': ['employee_first_name'],
                'permissions': (('change_ownprofile', 'Update own profile'), ('view_ownprofile', 'View Own Profile')),
                'unique_together': {('employee_first_name', 'employee_last_name', 'email')},
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('badge_id__isnull', False)), fields=['badge_id'], name='unique_badge_id'),
        ),
    ]
