# Generated by Django 4.2.21 on 2025-07-30 04:54

from django.db import migrations, models
from django.db import connection


def add_biometric_fields(apps, schema_editor):
    """Add biometric fields, handling any existing hikvision fields"""
    Employee = apps.get_model('employee', 'Employee')
    
    # Get table name
    table_name = Employee._meta.db_table
    cursor = connection.cursor()
    
    # Check existing columns
    cursor.execute(
        "SELECT column_name FROM information_schema.columns WHERE table_name=%s",
        [table_name]
    )
    existing_columns = [row[0] for row in cursor.fetchall()]
    
    # Remove hikvision fields if they exist
    if 'hikvision_employee_id' in existing_columns:
        cursor.execute(f'ALTER TABLE {table_name} DROP COLUMN hikvision_employee_id')
    if 'hikvision_employee_name' in existing_columns:
        cursor.execute(f'ALTER TABLE {table_name} DROP COLUMN hikvision_employee_name')
    
    # Add biometric fields if they don't exist
    if 'biometric_employee_id' not in existing_columns:
        cursor.execute(f'ALTER TABLE {table_name} ADD COLUMN biometric_employee_id VARCHAR(255) NULL')
    if 'biometric_employee_name' not in existing_columns:
        cursor.execute(f'ALTER TABLE {table_name} ADD COLUMN biometric_employee_name VARCHAR(255) NULL')


def reverse_biometric_fields(apps, schema_editor):
    """Reverse the migration"""
    Employee = apps.get_model('employee', 'Employee')
    table_name = Employee._meta.db_table
    cursor = connection.cursor()
    
    # Remove biometric fields
    cursor.execute(f'ALTER TABLE {table_name} DROP COLUMN IF EXISTS biometric_employee_id')
    cursor.execute(f'ALTER TABLE {table_name} DROP COLUMN IF EXISTS biometric_employee_name')


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_biometric_fields,
            reverse_biometric_fields
        ),
    ]
