# Generated by Django 4.2.21 on 2025-07-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biometric_employee_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Biometric Employee ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='biometric_employee_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Biometric Employee Name'),
        ),
    ]
